config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"recipes#index"
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show do
    member do
      get :favorites
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/classification.rb
class Classification < ActiveHash::Base
  self.data = [
    { id: 1, name: '分類を選ぶ' },
    { id: 2, name: '主食 - ごはん' },
    { id: 3, name: '主食 - パン' },
    { id: 4, name: '主食 - 麺' },
    { id: 5, name: 'おかず - 野菜' },
    { id: 6, name: 'おかず - 芋' },
    { id: 7, name: 'おかず - 豆腐・豆' },
    { id: 8, name: 'おかず - 乳製品' },
    { id: 9, name: 'おかず - 卵' },
    { id: 10, name: 'おかず - 魚' },
    { id: 11, name: 'おかず - 肉' },
    { id: 12, name: 'その他 - スープ' },
    { id: 13, name: 'その他 - デザート' }
  ]

  include ActiveHash::Associations
  has_many :recipes

  end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/moon_age.rb
class MoonAge < ActiveHash::Base
  self.data = [
    { id: 1, name: '月齢を選ぶ' },
    { id: 2, name: '5〜6ヶ月頃(初期)' },
    { id: 3, name: '7〜8ヶ月頃(中期)' },
    { id: 4, name: '9〜11ヶ月頃(後期)' },
    { id: 5, name: '12〜18ヶ月頃(完了期)' },
    { id: 6, name: '1歳半(幼児食)' },
    { id: 7, name: '指定しない' }
  ]
  include ActiveHash::Associations
  has_many :recipes

  end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :moon_age
  belongs_to :classification
  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :dish_name
    validates :ingredient
    validates :make
    validates :introduction
    validates :user_id
    validates :image
  end

  with_options numericality: { other_than: 1, message: "can't be blank" } do
    validates :moon_age_id
    validates :classification_id
  end

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  validates :user_name, presence: true
  has_many :recipes
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end

  def set_search
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comments = @recipe.comments.includes(:user)
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.recipe_id = @recipe.id
    @comment.save
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_comments = @recipe.comments
    @comments = @recipe.comments.includes(:user)
    Comment.find_by(id: params[:id], recipe_id: params[:recipe_id]).destroy
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  def create
    @recipe_favorite = Favorite.new(user_id: current_user.id, recipe_id: params[:recipe_id])
    @recipe_favorite.save
    redirect_back(fallback_location: root_path )
  end
  
  def destroy
    @recipe_favorite = Favorite.find_by(user_id: current_user.id, recipe_id: params[:recipe_id])
    @recipe_favorite.destroy
    redirect_back(fallback_location: root_path ) 
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_recipe, only: [:show, :destroy, :edit, :update,]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]
  def index
    @recipes = Recipe.order(id: 'DESC')
  end

  def new
    @recipe = Recipe.new
  end

  def show
    @comment = Comment.new #新規コメント用
    @comments = @recipe.comments.includes(:user) #コメント表示用投稿に関連づくコメントの取得
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      return redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def create
    @recipe = Recipe.create(recipe_params)
    if @recipe.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def search
    @q = Recipe.ransack(params[:q])
    @recipes = @q.result
  end

  private
  def recipe_params
    params.require(:recipe).permit(
      :dish_name,
      :ingredient,
      :make,
      :introduction,
      :image,
      :moon_age_id,
      :classification_id)
      .merge(user_id: current_user.id
      )
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @recipe.user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes
  end

  def favorites
    @user = User.find(params[:id])
    favorites= Favorite.where(user_id: @user.id).pluck(:recipe_id)
    @favorite_recipes = Recipe.find(favorites)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% @comments.each do |comment| %>
  <div class="comments_list">
    <div class="comments-title">
      <%= comment.user.user_name %>さんの投稿
    </div>
    <div class="comments-items">
      <div class="content">
        <%= comment.content %>
      </div>
      <div class="comment-delete">
      <% if current_user == comment.user %>
        <%=link_to "削除", recipe_comment_path(comment.recipe,comment), method: :delete, remote: true, class:"comment-delete" %>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comment_content").val("");
$('#comments').html("<%= escape_javascript(render 'comments', comment: @comment) %>")

app/views/comments/destroy.js.erb
$('#comments').html("<%= escape_javascript(render 'comments', comment: @comment) %>")

app/views/favorites/_favorites.html.erb
<% if user_signed_in? %> 
  <% if recipe.favorited?(current_user) %>
    <%= link_to recipe_favorites_path(recipe), method: :delete, class:"like-mark" do %>
      <span>❤︎</span><%= recipe.favorites.count %>
    <% end %>
    <% else %>
    <%= link_to recipe_favorites_path(recipe), method: :post, class:"like-mark" do %>
      <span>❤️</span><%= recipe.favorites.count %>
    <% end %>
    <% end %>
    <% else %>
    <%= link_to recipe_favorites_path(recipe), method: :post, class:"like-mark" do %>
      <span>❤️</span><%= recipe.favorites.count %>
    <% end %>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Babyfoodrecipe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zen+Kurenaido&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<%= render "shared/header" %>
<div class=show-main>
<div class="post-article-form">
  <%= form_with(model: @recipe, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :dish_name, '料理名' %><span>（必須）</span></p>
    <%= f.text_field :dish_name, class:"new-article-title", placeholder: "料理名" %>
    <p><%= f.label :ingredient, '材料' %><span>（必須）</span></p>
    <%= f.text_area :ingredient, class:"new-article-content", placeholder: "材料" %>
    <p><%= f.label :make, '作り方' %><span>（必須）</span></p>
    <%= f.text_area :make, class:"new-article-content", placeholder: "作り方" %>
    <p><%= f.label :introduction, '紹介文' %><span>（必須）</span></p>
    <%= f.text_area :introduction, class:"new-article-content", placeholder: "紹介文" %>
    <p><%= f.label :image, '離乳食画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <div class="change-recipe">
      <div class="edit-recipe">
        <%= f.submit "投稿", class:"edit-btn" %>
      </div>
      <div class="delete-recipe">
        <%= link_to "もどる", recipe_path(@recipe[:id]), class:"delete-btn" %>
      </div>  
    </div>
  <% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/recipes/index.html.erb
<%= render "shared/header" %>
<div class="main-contents">
  <div class="recipes">
    <% @recipes.each do |recipe| %>
     <%= link_to recipe_path(recipe) do %>
      <div class="recipe">
         <p class="recipe-content">
          <%= image_tag recipe.image, class: "recipe-image" if recipe.image.attached? %>
         </p>
         <p class="recipe-title">
          <%= recipe.dish_name %>
         <%= render "favorites/favorites", recipe: recipe %>
         </p>
       </div>
     <% end %>
    <% end %>
  </div>

  <div class="search">
   <p class="search-name"><%= link_to 'レシピ検索', search_recipes_path%></p>
    <%= search_form_for @q, url: search_recipes_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="search-name">
      <%= f.text_field :dish_name_cont, placeholder: 'レシピ名' %>
    </div>
    <div class="search-name">
      <%= f.label :moon_age_id_or_classification_id_eq, 'カテゴリ' %>
    </div>
    <div class="search-name">
      <%= f.collection_select(:moon_age_id_eq, MoonAge.where.not(id:1), :id, :name, {include_blank: "月齢を選ぶ"}, {class:"genre-select"}) %>
    </div>
    <div class="search-name">
      <%= f.collection_select(:classification_id_eq, Classification.where.not(id:1), :id, :name, {include_blank: "分類を選ぶ"}, {class:"genre-select"}) %>
    </div>
    <div class="search-name">
      <%= f.submit '検索' %>
    </div>
   <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recipes/new.html.erb
<%= render "shared/header" %>
<div class=show-main>
<div class="post-article-form">
  <%= form_with(model: @recipe, local: true) do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <p><%= f.label :dish_name, '料理名' %><span>（必須）</span></p>
    <%= f.text_field :dish_name, class:"new-article-title", placeholder: "料理名" %>
    <p><%= f.label :ingredient, '材料' %><span>（必須）</span></p>
    <%= f.text_area :ingredient, class:"new-article-content", placeholder: "材料" %>
    <p><%= f.label :make, '作り方' %><span>（必須）</span></p>
    <%= f.text_area :make, class:"new-article-content", placeholder: "作り方" %>
    <p><%= f.label :introduction, '紹介文' %><span>（必須）</span></p>
    <%= f.text_area :introduction, class:"new-article-content", placeholder: "紹介文" %>
    <p><%= f.label :image, '離乳食画像' %><span>（必須）</span></p>
    <%= f.file_field :image, class:"new-article-image", id:"new-article-image" %>
    <%= f.collection_select(:moon_age_id, MoonAge.all, :id, :name, {}, {class:"genre-select"}) %>
    <%= f.collection_select(:classification_id, Classification.all, :id, :name, {}, {class:"genre-select"}) %>
    <div class="return-toppage">
    <%= f.submit "投稿", class:"return-btn" %>
    </div>
  <% end %>
</div>
</div>
<%= render "shared/footer" %>

app/views/recipes/search.html.erb
<%= render "shared/header" %>
<div class="main-contents">
  <div class="recipes">
    <% @recipes.each do |recipe| %>
      <div class="recipe">
        <%= link_to recipe_path(recipe) do %>
         <p class="recipe-content">
          <%= image_tag recipe.image, class: "recipe-image" if recipe.image.attached? %>
         </p>
        <% end %>
         <p class="recipe-title">
          <%= recipe.dish_name%>
         </p>
      </div>
    <% end %>
  </div>

  <div class="search">
   <p class="search-name"><%= link_to 'レシピ検索', search_recipes_path%></p>
    <%= search_form_for @q, url: search_recipes_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="search-name">
      <%= f.search_field :dish_name_cont, placeholder: 'レシピ名' %>
    </div>
    <div class="search-name">
      <%= f.label :moon_age_id_or_classification_id_eq, 'カテゴリ' %>
    </div>
    <div class="search-name">
      <%= f.collection_select(:moon_age_id_eq, MoonAge.where.not(id:1), :id, :name, {include_blank: "月齢を選ぶ"}, {class:"genre-select"}) %>
    </div>
    <div class="search-name">
      <%= f.collection_select(:classification_id_eq, Classification.where.not(id:1), :id, :name, {include_blank: "分類を選ぶ"}, {class:"genre-select"}) %>
    </div>
    <div class="search-name">
      <%= f.submit '検索' %>
    </div>
   <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/recipes/show.html.erb
<%= render "shared/header" %>
<div class="show-wapper" >
  <div class=show-main>
    <div class="show-recipe">
      <p class="show-recipe-title">
        <%= @recipe.dish_name %>
      </p>
      <p class="show-recipe-content2">
        <%= @recipe.moon_age.name %>
      </p>
      <div class="show-recipe-content3">
        <%= @recipe.classification.name %>
      </div>
      <%= image_tag @recipe.image, class: "show-recipe-image" %>
      <% if user_signed_in? %>
        <% if @recipe.favorited?(current_user) %>
          <%= link_to recipe_favorites_path(@recipe), method: :delete, class:"mark" do %>
              <span style="color:red;">❤︎</span><%= @recipe.favorites.count %>
          <% end %>
        <% else %>
          <%= link_to recipe_favorites_path(@recipe), method: :post, class:"mark" do %>
              <span>❤︎</span><%= @recipe.favorites.count %>
          <% end %>
        <% end %>
        <% else %>
        <%= link_to recipe_favorites_path(@recipe), method: :post, class:"mark" do %>
              <span>❤︎</span><%= @recipe.favorites.count %>
          <% end %>
      <% end %>
      <div class="title">
          材料
      </div>
      <div class="show-recipe-content">
        <p class=content><%= safe_join(@recipe.ingredient.split("\n"),tag(:br)) %></p>
      </div>
      <div class="title">
          レシピ
      </div>
      <div class="show-recipe-content">
         <p class=content><%= safe_join(@recipe.make.split("\n"),tag(:br)) %></p>
      </div>
      <div class="title">
          紹介文
      </div>
      <div class="show-recipe-content">
         <p class=content><%= safe_join(@recipe.introduction.split("\n"),tag(:br)) %></p>
      </div>
      <div class="title">
          投稿者
      </div>
      <div class="show-recipe-content">
         <p class=content><%= @recipe.user.user_name %></p>
      </div>
    </div>
    <% if current_user == @recipe.user %>
      <div class="change-recipe">
        <div class="edit-recipe">
          <%= link_to "編集", edit_recipe_path(@recipe), class:"edit-btn" %>
        </div>
        <div class="delete-recipe">
          <%= link_to "削除", recipe_path(@recipe), method: :delete, class:"delete-btn" %>
        </div>
      </div>
    <% end %>
    <div class="return-toppage">
      <%= link_to "トップページへ戻る", root_path, class:"return-btn" %>
    </div>
  </div>
  <div class="recipe-comments">
    <div id="comments"><%= render 'comments/comments', comment: @comment %></div>
      <%= form_with model: [@recipe, @comment] do |f| %>
      <div class = 'form-group'>
        <%= f.text_area :content, class: "form-control", id:"comment_content", placeholder: "コメントを記入してください" %>
      </div>
        <%= f.submit "コメントする", class: "btn btn-primary" , id: "submit" %>
      <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%=link_to image_tag("logo_transparent.png", class:"footer-logo"), "/" %>
</div>

app/views/shared/_header.html.erb
<div class="header"> 
  <div class="logo">
    <%= link_to image_tag("/images/linkedin_banner_image_1.png", class:"header-icon"), "/" %>
  </div>
  <div class="header-btn">
    <% if user_signed_in? %>
      <%= link_to current_user.user_name, user_path(current_user), class: "post-article-btn" %>
      <%= link_to '投稿する', new_recipe_path, class:"post-article-btn"%>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout-btn"%>
    <% else %>
      <%= link_to 'ログイン', new_user_session_path, class: "post-article-btn" %>
      <%= link_to '新規登録', new_user_registration_path, class: "logout-btn" %>
    <%end%>
  </div>
  <div class="menu-bar">
  </div>
</div>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("logo_transparent.png", class:"second-logo"), "/" %>
</header>

app/views/users/favorites.html.erb
<%= render "shared/header" %>
<div class="main-contents">
  <div>
    <p class="user-show-name">
      <%= "#{@user.user_name}さんのお気に入り" %>
    </p>
    <%= link_to 'トップベージへ', root_path, class:"root-btn"%>
    <%= link_to 'もどる', user_path(current_user), class:"root-btn"%>
  </div>
  <div class="recipes1">
     <% @favorite_recipes.each do |recipe|%>
       <div class="recipe1">
        <%= link_to recipe_path(recipe) do %>
         <p class="recipe-content">
          <%= image_tag recipe.image, class: "recipe-image" if recipe.image.attached? %>
         </p>
        <% end %>
         <p class="recipe-title">
          <%= recipe.dish_name%>
         </p>
      </div>
     <% end %>
    </div>
</div>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="main-contents">
  <div>
    <p class="user-show-name">
      <%= "#{@user.user_name}さんのレシピ" %>
    </p>
    <%= link_to 'トップベージへ', root_path, class:"root-btn"%>
    <%= link_to 'お気に入りレシピ', favorites_user_path(@user), class:"root-btn"%>
  </div>
  <div class="recipes1">
     <% @recipes.each do |recipe| %>
      <div class="recipe1">
        <%= link_to recipe_path(recipe) do %>
         <p class="recipe-content">
          <%= image_tag recipe.image, class: "recipe-image" if recipe.image.attached? %>
         </p>
        <% end %>
         <p class="recipe-title">
          <%= recipe.dish_name%>
         </p>
      </div>
     <% end %>
  </div>
</div>
<%= render "shared/footer" %>